const fs=require('node:fs');
const ui=fs.readFileSync('src/ui.ts','utf8').replace('FISH.every(f=>s.discoveries[f.id])','FISH.filter(f=>s.discoveries[f.id]).length>=12');fs.writeFileSync('src/ui.ts',ui);
let readme=fs.readFileSync('README.md','utf8');
readme=readme.replace('清理后原位置可通行，进度永久保存、不隔夜重生。森林原有的小型木材和石料采集点仍每日恢复','清理后原位置可通行。树木从树苗开始，3 天后长成小树，6 天后成为可砍伐的大树；成熟时恢复碰撞。岩石清理进度永久保存。野外木材和石料采集点每 5 天恢复');
readme=readme.replace('地图内右上角的木质像素状态框集中显示日期、天气、季节图标、等级、昼夜指针、时间、金币和生命／体力／饱食','地图内右上角的半透明状态框用两行集中显示日期、天气、等级、时间、金币和生命／体力／饱食');
readme=readme.replace('角色走到遮挡区域时','角色接近右上角之前');
readme=readme.replace('在农场池塘或湖畔标记旁选择鱼竿并使用。','在农场池塘、湖畔、海湾或山脊湖的标记旁选择鱼竿并使用。浮标固定落在水面，紧凑小游戏面板就近显示；咬钩会显示放大的感叹号、金色提示和提示音。收竿后需等待 1.2 秒并松开按键或鼠标，才能再次抛竿。');
readme=readme.replace('原有农场、小屋、小镇、森林、湖畔之外新增两张地图：','原有农场、小屋、小镇、森林、湖畔之外，另有四张可解锁地图：');
readme=readme.replace('| 萤火秘林 | Lv.3，累计 100 经验 | 180 G | 野果、木材、萤火、每日 3 颗野苹果补给 |','| 萤火秘林 | Lv.3，累计 300 经验 | 180 G | 野果、木材、萤火、每 3 天领取 3 颗野苹果 |');
readme=readme.replace('| 回声石谷 | Lv.5，累计 280 经验 | 400 G | 密集石料点、古碑、每日 8 份石料矿藏 |','| 回声石谷 | Lv.5，累计 840 经验 | 400 G | 石料点、古碑、每 3 天领取 8 份石料 |\n| 潮声海湾 | Lv.4，累计 540 经验 | 350 G | 沙滩、海钓、漂流箱、银沙丁鱼与海鲈鱼 |\n| 云杉山脊 | Lv.6，累计 1260 经验 | 650 G | 松林、高山湖、观景台、草药与山石 |');
readme=readme.replace('在对应路牌旁按 E 查看并购买永久通行','湖畔南端通往海湾，石谷东侧通往山脊。在对应入口路牌旁按 E 查看并购买永久通行');
readme=readme.replace('等级最高为 10；经验仍可继续积累。','等级最高为 10；经验仍可继续积累。本版升级所需累计经验增加到原来的 3 倍。旧存档经验自动同比迁移一次，保留已经获得的等级与区域资格。');
readme=readme.replace('森林每天可重复探索：','森林可以持续探索，但要留时间给资源恢复：');
readme=readme.replace('领取 60 G 和 30 经验。','领取 60 G 和 30 经验；宝箱领取后需恢复 3 天。');
readme=readme.replace('每人每天一次','每 3 天一次').replace('15 经验，每天一次','15 经验，每 3 天一次');
readme=readme.replace('完成后光点消失；过夜刷新，刷新网页不会重复发奖。','完成后光点消失。线索和清泉每天恢复，奖励事件间隔 3 天；野外食材间隔 3 天、木石点间隔 5 天。农场免费莓果每天供应，保障零资源时也可恢复。刷新网页不会重复发奖。');
readme=readme.replace('8 种作物、12 种鱼','8 种作物、14 种鱼');
readme=readme.replace('小屋可主动睡觉。','小屋可主动睡觉，经过入夜、星光和晨光的短暂过渡后进入次日，只结算一次。衣柜以角色图例展示发型、服装和帽子，可先预览再确认。');
readme=readme.replace('商店每日 08:00–20:00 营业，','商店购买与出售使用不同颜色和明确标签，顶部突出当前余额，确认前显示交易总价与交易后余额。商店每日 08:00–20:00 营业，');
readme=readme.replace('七张地图','九张地图').replace('森林每日事件','森林探索事件');
readme=readme.replace('- `progression.ts`：','- `balance.ts` / `ecology.ts`：等级门槛、资源恢复间隔、树木生长与存档状态。\n- `overlays.ts`：钓鱼面板避让和 HUD 位置判断。\n- `progression.ts`：');
fs.writeFileSync('README.md',readme);
