import { describe,it,expect } from 'vitest';
import { initialState,clearGrass,farmAction,harvestResource,dayEnd,gather,repairFacility,restAtShelter,canFish,generateOrders } from './engine';
import { GRASS,grassAt,workTarget,REPAIRS,fishingSpots } from './fieldwork';
import { WorkController } from './work-session';
import { quantity,add } from './inventory';
import { parseSave,validSave } from './persistence';
import { SCENES,objectDistance,passable } from './world';
import { fishingAnchor } from './fishing';
const tree=()=>{const s=initialState(42);Object.assign(s.player,{x:10,y:4,direction:'up'});s.selectedTool='axe';return s;};
describe('ordinary ground grass',()=>{
  it('clears underfoot and adjacent grass without creating farmland',()=>{for(const dx of [0,1]){const s=initialState(1),g=GRASS.farm[0];Object.assign(s.player,{x:g.x+dx,y:g.y});expect(clearGrass(s,g.x,g.y).ok).toBe(true);expect(quantity(s.inventory,'fiber')).toBe(1);expect(s.player.vitals.stamina).toBe(98);expect(grassAt(s,g.x,g.y)).toBeUndefined();expect(farmAction(s,g.x,g.y).ok).toBe(false);expect(s.plots.some(p=>p.tilled)).toBe(false);expect(validSave(s)).toBe(true);}});
  it('does not charge for invalid tools, range, full bag or insufficient stamina',()=>{for(const reason of ['tool','range','bag','energy']){const s=initialState(1),g=GRASS.farm[0];Object.assign(s.player,{x:g.x,y:g.y});if(reason==='tool')s.selectedTool='axe';if(reason==='range')s.player.x+=4;if(reason==='bag')s.inventory.slots=Array.from({length:24},()=>({id:'wood',count:99}));if(reason==='energy')s.player.vitals.stamina=1;const before=JSON.stringify(s);expect(clearGrass(s,g.x,g.y).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);}});
  it('keeps farm grass cleared and restores wilderness only after five days',()=>{const s=initialState(1),a=GRASS.farm[0],b=GRASS.forest[0];Object.assign(s.player,{x:a.x,y:a.y});clearGrass(s,a.x,a.y);Object.assign(s.player,{scene:'forest',x:b.x,y:b.y});clearGrass(s,b.x,b.y);for(let i=1;i<=5;i++){dayEnd(s,false,()=>.9);s.player.scene='farm';expect(grassAt(s,a.x,a.y)).toBeUndefined();s.player.scene='forest';expect(!!grassAt(s,b.x,b.y)).toBe(i===5);}});
  it('keeps entrances, resources and fishing approaches free of grass',()=>{for(const scene of Object.values(SCENES))for(const g of GRASS[scene.id]){expect(passable(scene.id,g.x,g.y)).toBe(true);expect(scene.objects.some(o=>objectDistance(g.x,g.y,o)<=1)).toBe(false);expect(scene.exits.some(e=>Math.abs(e.x-g.x)+Math.abs(e.y-g.y)<=2)).toBe(false);}});
});
describe('multi-hit resource rules and input',()=>{
  it('requires the configured hits at all three tool tiers and drops once',()=>{for(const level of [0,1,2])for(const kind of ['tree','rock']){const s=tree();s.upgrades.tools=level;const hits=kind==='tree'?[6,4,3][level]:[4,3,2][level],x=kind==='tree'?10:8,y=kind==='tree'?3:8;if(kind==='rock'){Object.assign(s.player,{x:8,y:9});s.selectedTool='pick';}for(let n=1;n<=hits;n++){expect(harvestResource(s,x,y).ok).toBe(true);expect(quantity(s.inventory,kind==='tree'?'wood':'stone')).toBe(n===hits?(kind==='tree'?6:4)+level*2:0);}expect(s.player.vitals.stamina).toBe(100-hits);expect(harvestResource(s,x,y).ok).toBe(false);expect(validSave(s)).toBe(true);}});
  it('charges double for hunger and preserves progress when the last hit has no space',()=>{const s=tree();s.player.vitals.hunger=19;harvestResource(s,10,3);expect(s.player.vitals.stamina).toBe(98);s.fieldwork.damage['farm:f2']=10;s.inventory.slots=Array.from({length:24},()=>({id:'wood',count:99}));const before=JSON.stringify(s);expect(harvestResource(s,10,3).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);s.inventory.slots.pop();expect(harvestResource(s,10,3).ok).toBe(true);expect(quantity(s.inventory,'wood')).toBe(23*99+6);});
  it('does not give drops or charge before the animation reaches its impact',()=>{const s=tree(),w=new WorkController();w.start(s,10,3);w.tick(s,.15);expect(s.player.vitals.stamina).toBe(100);w.cancel();w.tick(s,.5);expect(s.fieldwork.damage).toEqual({});});
  it('one tap hits once; holding repeats but never starts another target after finishing',()=>{const s=tree(),w=new WorkController();w.input('key',true);w.start(s,10,3);w.input('key',false);for(let i=0;i<40;i++)w.tick(s,1/60);expect(s.fieldwork.damage['farm:f2']).toBe(2);w.input('key',true);w.start(s,10,3);for(let i=0;i<240;i++)w.tick(s,1/60);expect(quantity(s.inventory,'wood')).toBe(6);expect(w.session).toBeNull();const before=JSON.stringify(s);expect(w.start(s,10,3).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);w.input('key',false);});
  it('mouse and keyboard holds share one session without multiplying hits',()=>{const s=tree(),w=new WorkController();w.input('key',true);w.input('pointer',true);w.start(s,10,3);expect(w.start(s,10,3).ok).toBe(false);w.tick(s,.23);expect(s.player.vitals.stamina).toBe(99);w.input('pointer',false);w.cancel();expect(w.start(s,10,3).ok).toBe(false);w.input('key',false);expect(w.start(s,10,3).ok).toBe(true);});
  it('pauses all work without catch-up and rejects a moved or changed-tool target',()=>{for(const mode of ['move','tool','scene']){const s=tree(),w=new WorkController();w.start(s,10,3);w.tick(s,0);expect(w.session?.elapsed).toBe(0);if(mode==='move')s.player.y=9;if(mode==='tool')s.selectedTool='hoe';if(mode==='scene')s.player.scene='town';w.tick(s,.23);expect(s.player.vitals.stamina).toBe(100);expect(w.session).toBeNull();}});
  it('restores damage without restoring an in-flight action and regrows a fresh tree',()=>{const s=tree();harvestResource(s,10,3);let r=parseSave(JSON.stringify(s))!;expect(r.fieldwork.damage['farm:f2']).toBe(2);expect(new WorkController().session).toBeNull();for(let i=0;i<5;i++)harvestResource(r,10,3);for(let i=0;i<6;i++)dayEnd(r,false,()=>.9);expect(r.fieldwork.damage).toEqual({});Object.assign(r.player,{scene:'farm',x:10,y:4});expect(workTarget(r,10,3)).toBeTruthy();});
  it('takes two strikes to gather small material nodes and ore, then waits five days',()=>{const s=tree();s.progression.xp=1260;Object.assign(s.player,{scene:'ridge',x:27,y:7});s.selectedTool='pick';expect(gather(s,27,7).ok).toBe(true);expect(quantity(s.inventory,'quartz')).toBe(0);expect(gather(s,27,7).ok).toBe(true);expect(quantity(s.inventory,'quartz')).toBe(1);expect(gather(s,27,7).ok).toBe(false);for(let i=0;i<5;i++)dayEnd(s,false,()=>.9);Object.assign(s.player,{scene:'ridge',x:27,y:7});expect(workTarget(s,27,7)).toBeTruthy();});
});
describe('regional discoveries and repairs',()=>{
  it('collects free shells, restores them after three nights, and unlocks orders after discovery',()=>{const s=initialState(1);s.progression.xp=1260;Object.assign(s.player,{scene:'coast',x:10,y:5});s.player.vitals.stamina=0;expect(gather(s,10,5).ok).toBe(true);expect(quantity(s.inventory,'shell')).toBe(1);expect(gather(s,10,5).ok).toBe(false);expect(generateOrders(s,()=>.999).some(o=>o.item==='shell')).toBe(true);expect(generateOrders(initialState(1),()=>.999).some(o=>o.item==='shell')).toBe(false);for(let i=0;i<3;i++)dayEnd(s,false,()=>.9);Object.assign(s.player,{scene:'coast',x:10,y:5});expect(gather(s,10,5).ok).toBe(true);});
  it('repairs only beside the facility, consumes exact amounts once, and persists',()=>{for(const id of ['pier','shelter'] as const){const s=initialState(1),d=REPAIRS[id];s.gold=300;s.progression.xp=1260;for(const item of d.ingredients)add(s.inventory,item.id,item.count);const before=JSON.stringify(s);expect(repairFacility(s,id).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);Object.assign(s.player,{scene:d.scene,x:id==='pier'?10:14,y:id==='pier'?18:7});expect(repairFacility(s,id).ok).toBe(true);expect(s.gold).toBe(300-d.gold);for(const item of d.ingredients)expect(quantity(s.inventory,item.id)).toBe(0);expect(repairFacility(s,id).ok).toBe(false);expect(parseSave(JSON.stringify(s))!.fieldwork.repairs).toContain(id);}});
  it('does not partly consume materials or money on failed repair',()=>{const s=initialState(1);Object.assign(s.player,{scene:'coast',x:10,y:18});s.gold=100;add(s.inventory,'wood',20);const before=JSON.stringify(s);expect(repairFacility(s,'pier').ok).toBe(false);expect(JSON.stringify(s)).toBe(before);});
  it('opens extra shore fishing only after repair and always anchors inside the sea',()=>{const s=initialState(1);Object.assign(s.player,{scene:'coast',x:16,y:18});expect(canFish(s)).toBe(false);s.fieldwork.repairs.push('pier');expect(canFish(s)).toBe(true);expect(fishingSpots(s)).toHaveLength(6);const a=fishingAnchor(s)!;expect(a.x).toBeGreaterThan(13);expect(a.y).toBeLessThan(18);});
  it('rests once per day, does not waste the visit at full stamina, and never rewards on reload',()=>{const s=initialState(1);s.progression.xp=1260;Object.assign(s.player,{scene:'ridge',x:14,y:7});s.fieldwork.repairs=['shelter'];expect(restAtShelter(s).ok).toBe(false);s.player.vitals.stamina=80;expect(restAtShelter(s).ok).toBe(true);expect(s.player.vitals.stamina).toBe(95);expect(restAtShelter(parseSave(JSON.stringify(s))!).ok).toBe(false);dayEnd(s,false,()=>.9);Object.assign(s.player,{scene:'ridge',x:14,y:7});s.player.vitals.stamina=70;expect(restAtShelter(s).ok).toBe(true);});
  it('migrates missing fields and rejects forged grass, resource damage and repair states',()=>{const old:any=tree();delete old.fieldwork;expect(parseSave(JSON.stringify(old))!.fieldwork.repairs).toEqual([]);for(const mutate of [(s:any)=>s.fieldwork.damage.fake=3,(s:any)=>s.fieldwork.damage['farm:f2']=12,(s:any)=>s.fieldwork.repairs=['fake'],(s:any)=>s.fieldwork.clearedGrass.fake=0,(s:any)=>s.fieldwork.restDay=100]){const s=tree();mutate(s);expect(parseSave(JSON.stringify(s))).toBeNull();}});
});
