import { ITEMS } from './content';
import { MACHINES, MACHINE_KINDS, PEOPLE, PERSON_IDS, PROCESSING } from './life-content';
import { dialogue, likes, nearPerson, villagerNodes } from './villagers';
import { machineBusy, machineStatus, nearMachine } from './facilities';
import { ENCOUNTERS } from './encounters';
import { SCENES } from './world';
import { quantity } from './inventory';
import { levelOf } from './progression';
import type { GameStateV2, VillagerId } from './types';

const button=(text:string,action:string,id='',value='',disabled=false)=>`<button class="action-button" data-action="${action}" data-id="${id}" data-value="${value}" ${disabled?'disabled':''}>${text}</button>`;
const title=(name:string,sub:string)=>`<div class="modal-eyebrow">CREEKSIDE · A LIFE TO KEEP</div><h2 id="modalTitle">${name}</h2><p class="modal-subtitle">${sub}</p>`;
export function facilitiesPanel(s:GameStateV2,workshop=false){
  return `<div class="section-title">${workshop?'制作农场设施':'设施收纳'}</div><p class="info-note">${workshop?'基础设备按等级开放；特色配方来自村民故事。': '在农场空地或空田格摆放。布置时暂停时间，道路和操作位置保持畅通。'}</p><div class="card-grid life-machines">${MACHINE_KINDS.map(kind=>{const d=MACHINES[kind];return `<article class="content-card"><span class="machine-emblem ${kind}" aria-hidden="true">${{sprinkler:'╋',dryer:'♧',preserver:'▤',hive:'⬡'}[kind]}</span><h3>${d.name}</h3><p>${d.description}</p><small>收纳 ${s.facilities.stored[kind]} 台 · 已摆放 ${s.facilities.machines.filter(m=>m.kind===kind).length} 台</small>${workshop?`<p>Lv.${d.level} · ${d.gold} G<br>${d.ingredients.map(i=>`${ITEMS[i.id].name} ${quantity(s.inventory,i.id)}/${i.count}`).join(' · ')}</p>${button('制作一台','craftMachine',kind,'',levelOf(s)<d.level||s.gold<d.gold||!d.ingredients.every(i=>quantity(s.inventory,i.id)>=i.count))}`:button('选择位置','placeStart',kind,'',s.player.scene!=='farm'||s.facilities.stored[kind]<1)}</article>`;}).join('')}</div>`+(workshop?'':`<div class="section-title">农场中的设备</div>${s.facilities.machines.map(m=>`<article class="facility-row"><div><strong>${MACHINES[m.kind].name}</strong><small>格子 ${m.x}, ${m.y} · ${machineStatus(m)}</small></div><div class="button-row">${button('查看','open','machine:'+m.id)}${button('搬动','moveMachine',String(m.id),'',s.player.scene!=='farm'||machineBusy(m))}${button('收回','storeMachine',String(m.id),'',s.player.scene!=='farm'||machineBusy(m))}</div></article>`).join('')||'<p class="info-note">还没有摆放设施。达到 Lv.2 后去石叔工坊看看。</p>'}`);
}
export function lifeJournal(s:GameStateV2){
  return `<section class="life-journal"><div class="section-title">今日见闻</div>${s.encounters.daily.map(e=>`<p class="encounter-note ${e.claimed?'completed':''}"><b>${e.claimed?'✓': '◇'} ${ENCOUNTERS[e.id].name}</b><span>${e.claimed?'本次探索已结束':ENCOUNTERS[e.id].hint}</span><small>调查 ${e.clues.length}/${ENCOUNTERS[e.id].points.length-1}</small></p>`).join('')||'<p class="info-note">今天没有特别预告。雨后的森林、退潮的海湾，都值得留心。</p>'}<div class="section-title">溪谷的朋友</div><div class="card-grid">${PERSON_IDS.map(id=>{const p=s.social.people[id],d=PEOPLE[id],n=villagerNodes(s).find(n=>n.id==='npc:'+id);return `<article class="content-card"><h3>${d.name} <small>好感 ${p.hearts}/100</small></h3><div class="friend-meter"><i style="width:${p.hearts}%"></i></div><p>${d.story} · ${p.stage}/3</p><small>${n?'现在：'+SCENES[n.scene].name:'现在：休息中，08:00 后见'}</small><p>${p.stage===3?'✓ 纪念：'+d.reward+'配方与共同完成的小事':`${p.active?'进行中':'好感 '+[10,30,60][p.stage]+' 可接取'} · ${d.stages[p.stage]}`}</p>${button('人物手记','open','npc:'+id)}</article>`;}).join('')}</div><div class="section-title">生产与布置</div><p class="info-note">${s.facilities.machines.length} 台设备 · ${s.facilities.machines.filter(m=>m.output).length} 份产物待领取</p>${button('打开设施收纳','open','facilities')}</section>`;
}
export function lifePanel(s:GameStateV2,panel:string):string|null{
  if(panel==='facilities')return title('农场布置','让每一块空地，慢慢长成自己的样子。')+facilitiesPanel(s);
  if(panel.startsWith('npc:')){
    const id=panel.slice(4) as VillagerId,d=PEOPLE[id];if(!d)return null;const p=s.social.people[id],near=nearPerson(s,id);
    return title(d.name+'的手记',d.story)+`<div class="person-story"><canvas width="96" height="96" data-person="${id}" aria-label="${d.name}的像素肖像"></canvas><blockquote>${dialogue(s,id)}</blockquote></div><div class="friend-meter" aria-label="好感 ${p.hearts}/100"><i style="width:${p.hearts}%"></i></div><p>好感 ${p.hearts}/100 · ${p.talkedDay===s.calendar.day?'今天已经聊过':'每日首次交谈 +2'} · ${near?'就在身边':'当面交谈和送礼；雨雪天在店门附近'}</p>${button('聊一会儿','talk',id,'',!near)}<div class="section-title">${p.stage===3?'我们的纪念':'故事 · 第 '+(p.stage+1)+' 章'}</div><p>${p.stage===3?'已经解锁'+d.reward+'配方，地图上也留下了你们共同完成的小事。':d.stages[p.stage]}</p>${p.active?`<small>调查 ${p.clues.length} 处${p.caught?' · 已成功收鱼':''}${p.watered?' · 已完成自动浇水':''}${p.cooked?' · 已制作沙拉':''}</small>`:''}${p.stage<3?button(p.active?'完成这一章':'接下这件事','story',id,'',!near||p.hearts<[10,30,60][p.stage]||p.advancedDay===s.calendar.day):''}<div class="section-title">带一份心意</div><p class="info-note">${p.giftedDay===s.calendar.day?'今天已经送过礼物，明天再来。':'每天可送一份；喜爱 +10，普通 +5。点击物品先预览，再确认赠送。'}</p><div class="gift-list">${[...new Set(s.inventory.slots.map(i=>i.id))].filter(item=>ITEMS[item].kind!=='seed').map(item=>button(`${ITEMS[item].name}${likes(id,item)?' ♥':''}`,'open',`gift:${id}:${item}`,'',!near||p.giftedDay===s.calendar.day)).join('')||'<small>背包里暂时没有可以赠送的物品。</small>'}</div>`;
  }
  if(panel.startsWith('gift:')){const [,id,item]=panel.split(':');if(!PEOPLE[id as VillagerId]||!ITEMS[item])return null;return title('一份心意',`送给${PEOPLE[id as VillagerId].name}`)+`<p>将赠送 ${ITEMS[item].name} ×1，获得 ${likes(id as VillagerId,item)?10:5} 点好感。</p><div class="button-row">${button('确认赠送','gift',id,item)}${button('再想想','open','npc:'+id)}</div>`;}
  if(panel.startsWith('machine:')){
    const m=s.facilities.machines.find(m=>m.id===Number(panel.slice(8)));if(!m)return title('设施已收回','到设施收纳重新摆放。');
    const near=nearMachine(s,m);
    return title(MACHINES[m.kind].name,MACHINES[m.kind].description)+`<p class="production-status">${machineStatus(m)}</p>${m.output?button('领取产物','collectMachine',String(m.id),'',!near):''}${!near?'<p class="info-note">请走到设备脚下或相邻格投料、领取。</p>':''}<div class="card-grid">${PROCESSING.filter(r=>r.machine===m.kind).map(r=>{const locked=r.owner&&s.social.people[r.owner].stage<3;return `<article class="content-card"><h3>${ITEMS[r.id].name}</h3><p>${r.ingredients.map(i=>`${ITEMS[i.id].name} ${quantity(s.inventory,i.id)}/${i.count}`).join(' · ')}</p><small>${r.nights} 个夜晚 · 售价 ${ITEMS[r.id].sell} G</small>${locked?`<p>完成${PEOPLE[r.owner!].name}的故事解锁</p>`:button('投入一批','process',String(m.id),r.id,!near||machineBusy(m)||!r.ingredients.every(i=>quantity(s.inventory,i.id)>=i.count))}</article>`;}).join('')}</div><div class="button-row">${button('搬动','moveMachine',String(m.id),'',s.player.scene!=='farm'||machineBusy(m))}${button('收回','storeMachine',String(m.id),'',s.player.scene!=='farm'||machineBusy(m))}${button('设施收纳','open','facilities')}</div>`;
  }
  return null;
}
